In [1]:
import pandas as pd
import numpy as np

In [2]:
demo = pd.read_excel("CustomerDemographics.xlsx")
behavior = pd.read_excel("CustomerBehaviorData.xlsx")
credit = pd.read_excel("CreditConsumptionData.xlsx")

In [3]:
demo

,ID,account_type,gender,age,Income,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction
0,17051,current,M,30,MEDIUM,26.4,9,9,355,0
1,11491,current,M,37,LOW,14.4,7,7,485,0
2,7433,current,M,33,MEDIUM,3.2,1,1,764,0
3,14606,current,M,63,LOW,10.2,6,6,863,0
4,8381,saving,M,33,MEDIUM,26.4,6,6,523,0
...,...,...,...,...,...,...,...,...,...,...
19995,12512,current,M,35,MEDIUM,13.5,1,1,523,0
19996,14224,current,M,53,MEDIUM,9.9,7,7,723,1
19997,18740,current,M,62,HIGH,37.8,8,8,863,1
19998,18134,current,M,34,MEDIUM,12.6,4,4,882,0
19999,12413,current,M,27,LOW,3.5,8,8,447,1

In [5]:
behavior

,ID,cc_cons_apr,dc_cons_apr,cc_cons_may,dc_cons_may,cc_cons_jun,dc_cons_jun,cc_count_apr,cc_count_may,cc_count_jun,...,credit_count_may,debit_count_may,max_credit_amount_may,debit_amount_jun,credit_amount_jun,credit_count_jun,debit_count_jun,max_credit_amount_jun,loan_enq,emi_active
0,17051,2017.460,29066.66,15919.84,2197.00,3752.000,29798.00,1.0,4,35,...,47,20,41860.0,32734.75,80959.00,36,9,171200.0,Y,3448.84
1,11491,7687.000,1308.00,41888.92,2216.92,7060.530,3143.36,2.0,27,50,...,0,8,113367.0,60974.75,495080.00,5,3,15694.0,Y,3812.69
2,7433,9094.460,14825.95,3087.64,769.59,25602.595,1445.00,44.0,8,47,...,2,14,168000.0,425802.96,115707.38,7,58,28058.0,Y,9432.90
3,14606,3126.000,4616.33,8676.80,5923.00,6717.000,18747.00,4.0,30,1,...,45,44,57750.0,25537.91,63606.00,12,0,24459.0,Y,144.61
4,8381,24988.720,10091.23,10132.00,3477.00,4667.000,511.00,2.0,8,5,...,1,2,18405.0,64687.32,62353.35,49,35,31574.0,Y,1887.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,12512,4641.500,5979.58,6008.61,4410.00,41743.000,1884.00,26.0,1,4,...,35,11,32944.0,105488.53,125470.83,21,50,58037.0,Y,7870.88
19996,14224,4994.450,2805.37,23214.00,5870.00,1041.000,1008.73,37.0,56,50,...,5,8,8850.0,77112.66,86559.00,62,38,24110.0,Y,3668.30
19997,18740,3262.145,2871.00,7335.25,11774.04,4130.000,1413.00,12.0,77,1,...,10,108,35819.0,57192.48,80627.00,2,18,1769.0,Y,5450.34
19998,18134,12824.010,4866.00,12242.48,284.00,15132.770,37911.00,67.0,1,4,...,11,12,39083.0,82039.00,24332.00,117,64,37255.0,Y,59.29
19999,12413,26218.000,6615.00,2832.00,4642.00,1314.640,11355.00,7.0,1,84,...,7,13,22831.0,60035.50,76669.00,9,64,96213.0,Y,793.41

In [6]:
credit

          ID  cc_cons
0      17051  16239.0
1      11491  39002.0
2       7433  21182.0
3      14606   8123.0
4       8381  28282.0
...      ...      ...
19995  12512      NaN
19996  14224      NaN
19997  18740      NaN
19998  18134      NaN
19999  12413      NaN

[20000 rows x 2 columns]

In [8]:
demo.head(5)

,ID,account_type,gender,age,Income,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction
0,17051,current,M,30,MEDIUM,26.4,9,9,355,0
1,11491,current,M,37,LOW,14.4,7,7,485,0
2,7433,current,M,33,MEDIUM,3.2,1,1,764,0
3,14606,current,M,63,LOW,10.2,6,6,863,0
4,8381,saving,M,33,MEDIUM,26.4,6,6,523,0

In [9]:
behavior.head(5)

,ID,cc_cons_apr,dc_cons_apr,cc_cons_may,dc_cons_may,cc_cons_jun,dc_cons_jun,cc_count_apr,cc_count_may,cc_count_jun,...,credit_count_may,debit_count_may,max_credit_amount_may,debit_amount_jun,credit_amount_jun,credit_count_jun,debit_count_jun,max_credit_amount_jun,loan_enq,emi_active
0,17051,2017.46,29066.66,15919.84,2197.00,3752.000,29798.00,1.0,4,35,...,47,20,41860.0,32734.75,80959.00,36,9,171200.0,Y,3448.84
1,11491,7687.00,1308.00,41888.92,2216.92,7060.530,3143.36,2.0,27,50,...,0,8,113367.0,60974.75,495080.00,5,3,15694.0,Y,3812.69
2,7433,9094.46,14825.95,3087.64,769.59,25602.595,1445.00,44.0,8,47,...,2,14,168000.0,425802.96,115707.38,7,58,28058.0,Y,9432.90
3,14606,3126.00,4616.33,8676.80,5923.00,6717.000,18747.00,4.0,30,1,...,45,44,57750.0,25537.91,63606.00,12,0,24459.0,Y,144.61
4,8381,24988.72,10091.23,10132.00,3477.00,4667.000,511.00,2.0,8,5,...,1,2,18405.0,64687.32,62353.35,49,35,31574.0,Y,1887.89

In [10]:
credit.head(5)

      ID  cc_cons
0  17051  16239.0
1  11491  39002.0
2   7433  21182.0
3  14606   8123.0
4   8381  28282.0

In [11]:
demo.shape

(20000, 10)

In [12]:
behavior.shape

(20000, 39)

In [13]:
credit.shape

(20000, 2)

In [14]:
demo.isnull().sum()

ID                              0
account_type                    0
gender                          0
age                             0
Income                          0
Emp_Tenure_Years                0
Tenure_with_Bank                0
region_code                     0
NetBanking_Flag                 0
Avg_days_between_transaction    0
dtype: int64

In [15]:
behavior.isnull().sum()

ID                       0
cc_cons_apr              0
dc_cons_apr              0
cc_cons_may              1
dc_cons_may              1
cc_cons_jun              0
dc_cons_jun              1
cc_count_apr             1
cc_count_may             0
cc_count_jun             0
dc_count_apr             0
dc_count_may             0
dc_count_jun             0
card_lim                 0
personal_loan_active     0
vehicle_loan_active      0
personal_loan_closed     1
vehicle_loan_closed      0
investment_1             0
investment_2             0
investment_3             2
investment_4             0
debit_amount_apr         0
credit_amount_apr        0
debit_count_apr          1
credit_count_apr         0
max_credit_amount_apr    0
debit_amount_may         0
credit_amount_may        0
credit_count_may         0
debit_count_may          0
max_credit_amount_may    0
debit_amount_jun         0
credit_amount_jun        0
credit_count_jun         0
debit_count_jun          0
max_credit_amount_jun    0
loan_enq                 2
emi_active               1
dtype: int64

In [16]:
credit.isnull().sum()

ID            0
cc_cons    5000
dtype: int64

In [17]:
demo["ID"].duplicated().sum()

np.int64(0)

In [18]:
behavior["ID"].duplicated().sum()

np.int64(0)

In [19]:
credit["ID"].duplicated().sum()

np.int64(0)

In [20]:
df = demo.merge(behavior, on="ID", how="inner")
df = df.merge(credit, on="ID", how="inner")

print(df.shape)
print(df.head())

(20000, 49)
      ID account_type gender  age  Income  Emp_Tenure_Years  Tenure_with_Bank  \
0  17051      current      M   30  MEDIUM              26.4                 9
1  11491      current      M   37     LOW              14.4                 7
2   7433      current      M   33  MEDIUM               3.2                 1
3  14606      current      M   63     LOW              10.2                 6
4   8381       saving      M   33  MEDIUM              26.4                 6

   region_code  NetBanking_Flag  Avg_days_between_transaction  ...  \
0            9              355                             0  ...
1            7              485                             0  ...
2            1              764                             0  ...
3            6              863                             0  ...
4            6              523                             0  ...

   debit_count_may  max_credit_amount_may  debit_amount_jun  \
0               20                41860.0          32734.75
1                8               113367.0          60974.75
2               14               168000.0         425802.96
3               44                57750.0          25537.91
4                2                18405.0          64687.32

   credit_amount_jun  credit_count_jun  debit_count_jun  \
0           80959.00                36                9
1          495080.00                 5                3
2          115707.38                 7               58
3           63606.00                12                0
4           62353.35                49               35

   max_credit_amount_jun  loan_enq  emi_active  cc_cons
0               171200.0         Y     3448.84  16239.0
1                15694.0         Y     3812.69  39002.0
2                28058.0         Y     9432.90  21182.0
3                24459.0         Y      144.61   8123.0
4                31574.0         Y     1887.89  28282.0

[5 rows x 49 columns]

In [21]:
df

,ID,account_type,gender,age,Income,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction,...,debit_count_may,max_credit_amount_may,debit_amount_jun,credit_amount_jun,credit_count_jun,debit_count_jun,max_credit_amount_jun,loan_enq,emi_active,cc_cons
0,17051,current,M,30,MEDIUM,26.4,9,9,355,0,...,20,41860.0,32734.75,80959.00,36,9,171200.0,Y,3448.84,16239.0
1,11491,current,M,37,LOW,14.4,7,7,485,0,...,8,113367.0,60974.75,495080.00,5,3,15694.0,Y,3812.69,39002.0
2,7433,current,M,33,MEDIUM,3.2,1,1,764,0,...,14,168000.0,425802.96,115707.38,7,58,28058.0,Y,9432.90,21182.0
3,14606,current,M,63,LOW,10.2,6,6,863,0,...,44,57750.0,25537.91,63606.00,12,0,24459.0,Y,144.61,8123.0
4,8381,saving,M,33,MEDIUM,26.4,6,6,523,0,...,2,18405.0,64687.32,62353.35,49,35,31574.0,Y,1887.89,28282.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,12512,current,M,35,MEDIUM,13.5,1,1,523,0,...,11,32944.0,105488.53,125470.83,21,50,58037.0,Y,7870.88,NaN
19996,14224,current,M,53,MEDIUM,9.9,7,7,723,1,...,8,8850.0,77112.66,86559.00,62,38,24110.0,Y,3668.30,NaN
19997,18740,current,M,62,HIGH,37.8,8,8,863,1,...,108,35819.0,57192.48,80627.00,2,18,1769.0,Y,5450.34,NaN
19998,18134,current,M,34,MEDIUM,12.6,4,4,882,0,...,12,39083.0,82039.00,24332.00,117,64,37255.0,Y,59.29,NaN
19999,12413,current,M,27,LOW,3.5,8,8,447,1,...,13,22831.0,60035.50,76669.00,9,64,96213.0,Y,793.41,NaN

##### Average credit card transactions

In [23]:
df["Avg_CC_Spend"] = (
    df["cc_cons_apr"] + df["cc_cons_may"] + df["cc_cons_jun"]
) / 3

In [24]:
df["Avg_CC_Spend"]

0         7229.766667
1        18878.816667
2        12594.898333
3         6173.266667
4        13262.573333
             ...
19995    17464.370000
19996     9749.816667
19997     4909.131667
19998    13399.753333
19999    10121.546667
Name: Avg_CC_Spend, Length: 20000, dtype: float64

##### Average debit card transactions

In [25]:
df["Avg_DC_Spend"] = (
    df["dc_cons_apr"] + df["dc_cons_may"] + df["dc_cons_jun"]
) / 3

In [26]:
df["Avg_DC_Spend"]

0        20353.886667
1         2222.760000
2         5680.180000
3         9762.110000
4         4693.076667
             ...
19995     4091.193333
19996     3228.033333
19997     5352.680000
19998    14353.666667
19999     7537.333333
Name: Avg_DC_Spend, Length: 20000, dtype: float64

##### Total credit card transactions

In [27]:
df["Total_CC_Transactions"] = (
    df["cc_count_apr"] + df["cc_count_may"] + df["cc_count_jun"]
)

In [28]:
df["Total_CC_Transactions"]

0         40.0
1         79.0
2         99.0
3         35.0
4         15.0
         ...
19995     31.0
19996    143.0
19997     90.0
19998     72.0
19999     92.0
Name: Total_CC_Transactions, Length: 20000, dtype: float64

##### Total debit card transactions

In [30]:
df["Total_DC_Transactions"] = (
    df["dc_count_apr"] + df["dc_count_may"] + df["dc_count_jun"]
)

In [31]:
df["Total_DC_Transactions"]

0         21
1         19
2         32
3         78
4         45
        ...
19995     29
19996     77
19997     20
19998    112
19999     55
Name: Total_DC_Transactions, Length: 20000, dtype: int64

In [32]:
df.describe()

,ID,age,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction,cc_cons_apr,dc_cons_apr,cc_cons_may,...,credit_amount_jun,credit_count_jun,debit_count_jun,max_credit_amount_jun,emi_active,cc_cons,Avg_CC_Spend,Avg_DC_Spend,Total_CC_Transactions,Total_DC_Transactions
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,1.999900e+04,...,2.000000e+04,20000.000000,20000.000000,2.000000e+04,1.999900e+04,15000.000000,19999.000000,19998.000000,19999.000000,20000.000000
mean,9999.500000,47.672300,15.217250,5.496050,5.496050,598.929400,0.718000,17856.990922,8130.453414,1.618836e+04,...,7.881693e+04,19.905450,44.529100,5.284985e+04,1.539887e+04,9369.030957,15394.012349,7647.459939,116.649382,61.620600
std,5773.647028,30.359771,20.481455,2.870452,2.870452,220.140472,0.449985,25158.878234,14572.188829,2.651068e+04,...,1.569872e+05,27.055323,35.080453,1.343175e+05,1.202541e+05,7552.997163,13780.887190,8876.582062,120.036511,38.972217
min,0.000000,25.000000,0.500000,1.000000,1.000000,0.000000,0.000000,253.000000,19.350000,1.570000e+02,...,1.188000e+01,1.000000,0.000000,6.000000e-02,0.000000e+00,610.099000,435.000000,232.796667,3.000000,3.000000
25%,4999.750000,33.000000,5.100000,3.000000,3.000000,424.000000,0.000000,4377.000000,1624.650000,3.635910e+03,...,2.492008e+04,4.000000,12.000000,1.896450e+04,1.545940e+03,4808.621700,7257.101667,3212.261667,55.000000,29.000000
50%,9999.500000,40.000000,9.900000,6.000000,6.000000,623.000000,1.000000,10214.642500,3964.750000,8.635230e+03,...,4.618300e+04,7.000000,37.000000,3.025000e+04,3.934660e+03,7408.604400,11717.256667,5318.500000,90.000000,58.000000
75%,14999.250000,53.000000,18.000000,8.000000,8.000000,799.000000,1.000000,21189.000000,9339.020000,1.865531e+04,...,8.602000e+04,21.000000,73.000000,5.344900e+04,9.376390e+03,11518.832800,18891.495000,8965.695000,134.000000,87.000000
max,19999.000000,223.000000,203.000000,10.000000,10.000000,974.000000,1.000000,441031.330000,229255.000000,1.117246e+06,...,6.611953e+06,117.000000,133.000000,5.200000e+06,7.447125e+06,160735.934800,387231.370000,310904.150000,1249.000000,229.000000

In [33]:
df.to_excel("Final_Credit_Consumption_Cleaned.xlsx", index=False)